# permissions for end users to view hostdefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostdefinition-viewer-role
rules:
- apiGroups:
  - csi.ibm.com
  resources:
  - hostdefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - csi.ibm.com
  resources:
  - hostdefinitions/status
  verbs:
  - get
