
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ibm-block-csi-operator
rules:
- apiGroups:
  - csi.ibm.com
  resources:
  - hostdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csi.ibm.com
  resources:
  - hostdefinitions/finalizers
  verbs:
  - update
- apiGroups:
  - csi.ibm.com
  resources:
  - hostdefinitions/status
  verbs:
  - get
  - patch
  - update
