apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: ibm-block-csi-operator-group
  labels:
    app.kubernetes.io/name: ibm-block-csi-operator
    app.kubernetes.io/instance: ibm-block-csi-operator
    app.kubernetes.io/managed-by: ibm-block-csi-operator
    release: ibm-block-csi-operator
spec:
  targetNamespaces:
  - DYNAMIC_NAMESPACE
