apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-block-csi-operator
  labels:
    app.kubernetes.io/name: ibm-block-csi-operator
    app.kubernetes.io/instance: ibm-block-csi-operator
    app.kubernetes.io/managed-by: ibm-block-csi-operator
    release: ibm-block-csi-operator
spec:
  channel: stable
  name: ibm-block-csi-operator
  source: ibm-block-csi-operator
  sourceNamespace: openshift-marketplace
  startingCSV: ibm-block-csi-operator.v1.3.0
  installPlanApproval: Automatic
