name: Operator Builds
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
jobs:
  prepare_env:
   name: "Prepare env"
   runs-on: ubuntu-latest
   steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Setup dependencies
        id: setup_dependencies
        run: |
          build/ci/github_actions/setup_ci_dependencies.sh
        env:
          build_number: "${{ github.run_number }}"
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('dev-requirements.txt') }}
      - name: Save dependencies files
        uses: actions/upload-artifact@v2
        with:
          name: ci_dependencies
          path: |
            /home/runner/.bash_profile
          retention-days: 1
   outputs:
     image_branch_tag: "${{ steps.setup_dependencies.outputs.image_branch_tag }}"
     operator_specific_tag_for_test: "${{ steps.setup_dependencies.outputs.operator_specific_tag_for_test }}"
          
  csi_build_and_push_images:
    name: "CSI Build and push images"
    runs-on: ubuntu-latest
    needs:
      - prepare_env
    strategy:
      matrix:
        image_type: ['operator']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.3.0
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Build and push ${{ matrix.image_type }}
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/ppc64le,linux/s390x
          push: false
          tags: |
            ${{ secrets.CSIBLOCK_DOCKER_REGISTRY_USERNAME }}/ibm-block-csi-${{ matrix.image_type }}:${{ needs.prepare_env.outputs.operator_specific_tag_for_test }}
            ${{ secrets.CSIBLOCK_DOCKER_REGISTRY_USERNAME }}/ibm-block-csi-${{ matrix.image_type }}:${{ needs.prepare_env.outputs.image_branch_tag }}
          file: build/Dockerfile.${{ matrix.image_type }}
          cache-from: type=local,src=/tmp/.buildx-${{ matrix.image_type }}
          cache-to: type=local,dest=/tmp/.buildx-new-${{ matrix.image_type }}
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
